title: George Onchaba, Senior Backend Engineer
description: This is my official portfolio. I have listed some of my projects and work experience.

# GitHub repository settings
repository:
  name: gee-cpu/gee-cpu.github.io
  branch: master # Consider using "main" as the default branch name

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE

# Jekyll SEO settings
seo:
  name: George Onchaba
  social:
    - name: twitter
      url: https://twitter.com/ogee70607478
    - name: github
      url: https://github.com/gee-cpu
    - name: linkedIn
      url: https://linkedin.com/in/gonchaba

# Additional settings for HTML, CSS, and styles
# Customize the following paths based on your actual file structure
include:
  - _layouts
  - _includes
  - assets

# Skills section
skills:
  - category: Java
    list:
      - Core
      - Spring
      - Spring Boot
  - category: DevOps
    list:
      - Docker
      - Kubernetes
  - category: Databases
    list:
      - MySQL
      - PostgreSQL
      - MongoDB
  - category: Messaging
    list:
      - RabbitMQ
      - JMS
  - category: Build Tools
    list:
      - Maven
      - Gradle
  - category: Version Control
    list:
      - Git
  - category: Testing
    list:
      - Selenium
      - JUnit
      - BDD
      - TDD
  - category: CI/CD
    list:
      - Jenkins
  - category: Web Services
    list:
      - REST
      - GraphQL
  - category: Security
    list:
      - Spring Security
  - category: Project Management
    list:
      - Jira
      - Confluence
