server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: google-maps
          uri: lb://google-maps-integration
          predicates:
            - Path=/google-maps/**
          filters:
            - name: CircuitBreaker
              args:
                name: google-maps-integration
                fallbackuri: forward:/mapsServicefallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: places
          uri: lb://google-maps-integration
          predicates:
            - Path=/places/**
          filters:
            - name: CircuitBreaker
              args:
                name: google-maps-integration
                fallbackuri: forward:/mapsServicefallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: geocoding
          uri: lb://google-maps-integration
          predicates:
            - Path=/geocode/**
          filters:
            - name: CircuitBreaker
              args:
                name: google-maps-integration
                fallbackuri: forward:/mapsServicefallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: directions
          uri: lb://google-maps-integration
          predicates:
            - Path=/directions/**
          filters:
            - name: CircuitBreaker
              args:
                name: google-maps-integration
                fallbackuri: forward:/mapservicefallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: crime-service-crimes
          uri: lb://crime-service
          predicates:
            - Path=/api/crimes/**
          filters:
            - name: CircuitBreaker
              args:
                name: crime-service
                fallbackuri: forward:/crimeservicefallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: crime-service-users
          uri: lb://crime-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: crime-service
                fallbackuri: forward:/crimeservicefallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  config:
    import:
      config-server: ${CONFIG_SERVER}http://localhost:9296

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
okta:
  oauth2:
    issuer: https://dev-44453706.okta.com/oauth2/default
    audience: api://default
    client-id: 0oadsyp6j7ur9KEs85d7
    client-secret: GOfasQdsTma1ue7nlw9KI-X60blaQ7k5ZDIl9rbX12emwn-SADk2R9IHzatVPTmd
    scopes: openid, profile, email, offline_access